### ISSUE TITLE
Some occupations not available to some Civilian ranks

### ISSUE THREAD

**Issue by TheTrollDoctor** [Indiebay/indie-bay#7]
#### Specific information for locating

Science roles only open to NT
Forensic Tech, Physician only available to Contractors

#### Client version, Server revision & Game ID

Client Version: 511
Server Revision: Revision Unknown
Game ID: bTD-ccip
Current map: ISV Clear Skies

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Indiebay/indie-bay/issues/)

**Comment by Andromeda-K22** [comment]
`/datum/job/detective
	title = "Forensic Technician"
	total_positions = 1
	spawn_positions = 1
	supervisors = "the Chief of Security"
	economic_modifier = 5
	minimal_player_age = 7
	ideal_character_age = 35
	alt_titles = list(
		"Criminal Investigator",
		"Detective"
	)
	outfit_type = /decl/hierarchy/outfit/job/torch/crew/security/forensic_tech
	allowed_branches = list(
		/datum/mil_branch/fleet = /decl/hierarchy/outfit/job/torch/crew/security/forensic_tech/fleet,
		/datum/mil_branch/civilian,
		/datum/mil_rank/frontier
	)
	allowed_ranks = list(
		/datum/mil_rank/fleet/e3,
		/datum/mil_rank/fleet/e4,
		/datum/mil_rank/fleet/e5,
		/datum/mil_rank/civ = /decl/hierarchy/outfit/job/torch/crew/security/forensic_tech/contractor
	)`

`/datum/job/senior_doctor
	title = "Physician"
	department = "Medical"
	department_flag = MED

	minimal_player_age = 14
	ideal_character_age = 45
	total_positions = 2
	spawn_positions = 2
	supervisors = "the Chief Medical Officer"
	selection_color = "#013d3b"
	economic_modifier = 8
	alt_titles = list(
		"Surgeon",
		"Trauma Surgeon")
	outfit_type = /decl/hierarchy/outfit/job/torch/crew/medical/senior
	allowed_branches = list(
		/datum/mil_branch/fleet = /decl/hierarchy/outfit/job/torch/crew/medical/senior/fleet
	)
	allowed_ranks = list(
		/datum/mil_rank/civ,
		/datum/mil_rank/fleet/o2,
		/datum/mil_rank/fleet/o1
	)
`

**Comment by Andromeda-K22** [comment]
Formatting in the above comment is fucked, but these jobs are not just available to civilians. Ranks *do* exist for Fleet.
